server:
  port: 8002
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
      # 服务续约（心跳）频率，单位：秒，缺省30
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false