server:
  port: 6000

spring:
  application:
    name: servicediscovery

eureka:
  instance:
    hostname: localhost2
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
    ip-address: 127.0.0.1
  server:
    wait-time-in-ms-when-sync-empty: 5
    enableSelfPreservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.1:7000/eureka/

logging:
  level:
    org:
      springframework: INFO