server:
  port: 8001

spring:
  application:
    name: userservice

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        physical_naming_strategy: com.zhaops.userservice.util.HibernatePhysicalNamingNamingStrategy
    database: H2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://172.16.100.177:8000/eureka